import { shellPermissionCodes } from './core/shellRegistry';

type InitialState = {
  permissions?: readonly string[];
};

export default function access(initialState: InitialState = {}) {
  const permissions = new Set(initialState.permissions ?? []);
  const hasPermission = (permissionCode: string) =>
    permissions.has(permissionCode);
  const hasAnyPermission = (...permissionCodes: readonly string[]) =>
    permissionCodes.some((permissionCode) => hasPermission(permissionCode));

  return {
    canAccessDashboard: hasPermission('core:dashboard:read'),
    canReadTenants: hasPermission('platform:tenant:read'),
    canCreateTenants: hasPermission('platform:tenant:create'),
    canUpdateTenants: hasPermission('platform:tenant:update'),
    canSuspendTenants: hasPermission('platform:tenant:suspend'),
    canVisitTenants: hasPermission('platform:tenant:visit'),
    canReadTenantPlans: hasPermission('platform:tenant-plan:read'),
    canManageTenantPlans: hasPermission('platform:tenant-plan:manage'),
    canReadTenantMembers: hasPermission('platform:tenant-member:read'),
    canManageTenantMembers: hasPermission('platform:tenant-member:manage'),
    canReadOpenApiStatus: hasPermission('tool:openapi:read'),
    canReadUsers: hasPermission('core:user:read'),
    canAssignUserRoles: hasPermission('core:user:manage'),
    canExportUsers: hasPermission('core:user:export'),
    canImportUsers: hasPermission('core:user:import'),
    canReadRoles: hasPermission('core:role:read'),
    canReadPermissions: hasPermission('core:permission:read'),
    canReadMenus: hasPermission('core:menu:read'),
    canReadDicts: hasPermission('core:dict:read'),
    canCreateDicts: hasPermission('core:dict:create'),
    canUpdateDicts: hasPermission('core:dict:update'),
    canDeleteDicts: hasPermission('core:dict:delete'),
    canExportDicts: hasPermission('core:dict:export'),
    canManageDicts: hasPermission('core:dict:manage'),
    canReadSystemConfig: hasPermission('core:config:read'),
    canExportSystemConfig: hasPermission('core:config:export'),
    canReadSystemNotices: hasPermission('core:notice:read'),
    canReadDepartments: hasPermission('core:dept:read'),
    canReadPosts: hasPermission('core:post:read'),
    canReadFiles: hasPermission('core:file:read'),
    canReadAuditLogs: hasPermission('core:audit-log:read'),
    canDeleteAuditLogs: hasPermission('core:audit-log:delete'),
    canReadLoginLogs: hasPermission('core:login-log:read'),
    canDeleteLoginLogs: hasPermission('core:login-log:delete'),
    canManageLoginLogs: hasPermission('core:login-log:manage'),
    canReadSystemStatus: hasPermission('monitor:status:read'),
    canReadVersion: hasPermission('monitor:version:read'),
    canReadQueues: hasPermission('monitor:queue:read'),
    canManageQueues: hasPermission('monitor:queue:manage'),
    canReadExportTools: hasPermission('tool:export:read'),
    canReadAreaData: hasPermission('system:area:read'),
    canImportAreaData: hasPermission('system:area:import'),
    canManageAreaData: hasPermission('system:area:manage'),
    canReadOpenForge: hasPermission('tool:openforge:read'),
    canManageOpenForge: hasPermission('tool:openforge:manage'),
    canReadMessages: hasPermission('collaboration:message:read'),
    canReadNotices: hasPermission('collaboration:notice:read'),
    canReadTodos: hasPermission('collaboration:todo:read'),
    canReadTickets: hasPermission('collaboration:ticket:read'),
    canCreateTickets: hasPermission('collaboration:ticket:create'),
    canUpdateTickets: hasPermission('collaboration:ticket:update'),
    canAssignTickets: hasPermission('collaboration:ticket:assign'),
    canCommentTickets: hasPermission('collaboration:ticket:comment'),
    canCloseTickets: hasPermission('collaboration:ticket:close'),
    canDeleteTickets: hasPermission('collaboration:ticket:delete'),
    canReadApprovalLite: hasPermission('collaboration:approval-lite:read'),
    canReadBusiness: hasAnyPermission(
      'business:core:read',
      'business:sales:read',
    ),
    canCreateBusiness: hasAnyPermission(
      'business:core:create',
      'business:sales:create',
    ),
    canUpdateBusiness: hasAnyPermission(
      'business:core:update',
      'business:sales:update',
    ),
    canAssignBusiness: hasAnyPermission(
      'business:core:assign',
      'business:sales:assign',
    ),
    canCommentBusiness: hasPermission('business:core:comment'),
    canExportBusiness: hasAnyPermission(
      'business:core:export',
      'business:sales:export',
    ),
    canDeleteBusiness: hasAnyPermission(
      'business:core:delete',
      'business:sales:delete',
    ),
    canReadJobs: hasPermission('monitor:job:read'),
    canUpdateJobs: hasPermission('monitor:job:update'),
    canManageJobs: hasPermission('monitor:job:manage'),
    canReadCache: hasPermission('monitor:cache:read'),
    canManageCache: hasPermission('monitor:cache:manage'),
    canReadOnlineUsers: hasPermission('monitor:online-user:read'),
    canManageOnlineUsers: hasPermission('monitor:online-user:manage'),
    canReadReports: hasPermission('optional:report:read'),
    canReadExportJobs: hasPermission('optional:export-job:read'),
    canReadIntegrationProviders: hasPermission('integration:provider:read'),
    canUpdateIntegrationProviders: hasPermission('integration:provider:update'),
    canManageIntegrationProviders: hasPermission('integration:provider:manage'),
    canReadMailIntegration: hasPermission('integration:mail:read'),
    canReadSmsIntegration: hasPermission('integration:sms:read'),
    canReadOAuthIntegration: hasPermission('integration:oauth:read'),
    canManageOAuthIntegration: hasPermission('integration:oauth:manage'),
    canReadWeChatIntegration: hasPermission('integration:wechat:read'),
    canReadWebSocketIntegration: hasPermission('integration:websocket:read'),
    canReadBillingDesign: hasPermission('integration:billing-design:read'),
    canReadHealth: hasPermission('core:dashboard:read'),
    hasAllShellPermissions: shellPermissionCodes.every((permissionCode) =>
      hasPermission(permissionCode),
    ),
  };
}
