export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user/login',
        name: 'login',
        component: './user/login',
      },
      {
        path: '/user/social-login',
        name: 'socialLogin',
        component: './user/social-login',
      },
      {
        path: '/user',
        redirect: '/user/login',
      },
      {
        name: 'exception.404',
        component: './Exception/404',
        path: '/user/*',
      },
    ],
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'dashboard',
    component: './Dashboard',
    access: 'canAccessDashboard',
  },
  {
    path: '/personal/profile',
    name: 'profile',
    component: './Personal/Profile',
    hideInMenu: true,
  },
  {
    path: '/system',
    name: 'system',
    icon: 'setting',
    routes: [
      { path: '/system', redirect: '/system/users' },
      {
        name: 'tenants',
        path: '/system/tenants',
        component: './System/Tenants',
        access: 'canReadTenants',
      },
      {
        name: 'users',
        path: '/system/users',
        component: './System/Users',
        access: 'canReadUsers',
      },
      {
        name: 'roles',
        path: '/system/roles',
        component: './System/Roles',
        access: 'canReadRoles',
      },
      {
        name: 'permissions',
        path: '/system/permissions',
        component: './System/Permissions',
        access: 'canReadPermissions',
      },
      {
        name: 'menus',
        path: '/system/menus',
        component: './System/Menus',
        access: 'canReadMenus',
      },
      {
        name: 'dicts',
        path: '/system/dicts',
        component: './System/Dicts',
        access: 'canReadDicts',
      },
      {
        name: 'config',
        path: '/system/config',
        component: './System/Config',
        access: 'canReadSystemConfig',
      },
      {
        name: 'notices',
        path: '/system/notices',
        component: './System/Notices',
        access: 'canReadSystemNotices',
      },
      {
        name: 'depts',
        path: '/system/depts',
        component: './System/Departments',
        access: 'canReadDepartments',
      },
      {
        name: 'posts',
        path: '/system/posts',
        component: './System/Posts',
        access: 'canReadPosts',
      },
      {
        name: 'files',
        path: '/system/files',
        component: './System/Files',
        access: 'canReadFiles',
      },
      {
        name: 'area',
        path: '/system/area',
        component: './System/Area',
        access: 'canReadAreaData',
      },
    ],
  },
  {
    path: '/security',
    name: 'security',
    icon: 'safety',
    routes: [
      { path: '/security', redirect: '/security/login-logs' },
      {
        name: 'loginLogs',
        path: '/security/login-logs',
        component: './Security/LoginLogs',
        access: 'canReadLoginLogs',
      },
      {
        name: 'operationLogs',
        path: '/security/operation-logs',
        component: './Security/OperationLogs',
        access: 'canReadAuditLogs',
      },
    ],
  },
  {
    path: '/monitor',
    name: 'monitor',
    icon: 'monitor',
    routes: [
      { path: '/monitor', redirect: '/monitor/status' },
      {
        name: 'status',
        path: '/monitor/status',
        component: './Monitor/Status',
        access: 'canReadSystemStatus',
      },
      {
        name: 'version',
        path: '/monitor/version',
        component: './Monitor/Version',
        access: 'canReadVersion',
      },
      {
        name: 'queues',
        path: '/monitor/queues',
        component: './Monitor/Queues',
        access: 'canReadQueues',
      },
      {
        name: 'jobs',
        path: '/monitor/jobs',
        component: './Monitor/Jobs',
        access: 'canReadJobs',
      },
      {
        name: 'cache',
        path: '/monitor/cache',
        component: './Monitor/Cache',
        access: 'canReadCache',
      },
      {
        name: 'onlineUsers',
        path: '/monitor/online-users',
        component: './Monitor/OnlineUsers',
        access: 'canReadOnlineUsers',
      },
    ],
  },
  {
    path: '/tools',
    name: 'tools',
    icon: 'tool',
    routes: [
      { path: '/tools', redirect: '/tools/openapi' },
      {
        name: 'openapi',
        path: '/tools/openapi',
        component: './Tools/OpenApi',
        access: 'canReadOpenApiStatus',
      },
      {
        name: 'export',
        path: '/tools/export',
        component: './Tools/Export',
        access: 'canReadExportTools',
      },
      {
        path: '/tools/area',
        redirect: '/system/area',
        hideInMenu: true,
      },
      {
        name: 'openforge',
        path: '/tools/openforge',
        component: './Tools/OpenForge',
        access: 'canReadOpenForge',
      },
    ],
  },
  {
    path: '/collaboration',
    name: 'collaboration',
    icon: 'team',
    routes: [
      { path: '/collaboration', redirect: '/collaboration/messages' },
      {
        name: 'messages',
        path: '/collaboration/messages',
        component: './Collaboration/Messages',
        access: 'canReadMessages',
      },
      {
        name: 'notices',
        path: '/collaboration/notices',
        component: './Collaboration/Notices',
        access: 'canReadNotices',
      },
      {
        name: 'todos',
        path: '/collaboration/todos',
        component: './Collaboration/Todos',
        access: 'canReadTodos',
      },
      {
        name: 'tickets',
        path: '/collaboration/tickets',
        component: './Collaboration/Tickets',
        access: 'canReadTickets',
      },
      {
        name: 'approvals',
        path: '/collaboration/approvals',
        component: './Collaboration/Approvals',
        access: 'canReadApprovalLite',
      },
    ],
  },
  {
    path: '/business',
    name: 'business',
    icon: 'apartment',
    routes: [
      { path: '/business', redirect: '/business/overview' },
      {
        name: 'overview',
        path: '/business/overview',
        component: './Business/overview',
        access: 'canReadBusiness',
      },
      {
        name: 'leads',
        path: '/business/leads',
        component: './Business/leads',
        access: 'canReadBusiness',
      },
      {
        name: 'pool',
        path: '/business/pool',
        component: './Business/pool',
        access: 'canReadBusiness',
      },
      {
        name: 'accounts',
        path: '/business/accounts',
        component: './Business/accounts',
        access: 'canReadBusiness',
      },
      {
        name: 'contacts',
        path: '/business/contacts',
        component: './Business/contacts',
        access: 'canReadBusiness',
      },
      {
        name: 'opportunities',
        path: '/business/opportunities',
        component: './Business/opportunities',
        access: 'canReadBusiness',
      },
      {
        name: 'lifecycle',
        path: '/business/lifecycle',
        component: './Business/lifecycle',
        access: 'canReadBusiness',
      },
      {
        name: 'tasks',
        path: '/business/tasks',
        component: './Business/tasks',
        access: 'canReadBusiness',
      },
      {
        name: 'tags',
        path: '/business/tags',
        component: './Business/tags',
        access: 'canReadBusiness',
      },
      {
        name: 'activity',
        path: '/business/activity',
        component: './Business/activity',
        access: 'canReadBusiness',
      },
      {
        name: 'products',
        path: '/business/products',
        component: './Business/products',
        access: 'canReadBusiness',
      },
      {
        name: 'quotes',
        path: '/business/quotes',
        component: './Business/quotes',
        access: 'canReadBusiness',
      },
      {
        name: 'contracts',
        path: '/business/contracts',
        component: './Business/contracts',
        access: 'canReadBusiness',
      },
      {
        name: 'receivables',
        path: '/business/receivables',
        component: './Business/receivables',
        access: 'canReadBusiness',
      },
    ],
  },
  {
    path: '/optional',
    name: 'optional',
    icon: 'appstore',
    routes: [
      { path: '/optional', redirect: '/optional/reports' },
      {
        name: 'reports',
        path: '/optional/reports',
        component: './Optional/Reports',
        access: 'canReadReports',
      },
      {
        name: 'exportJobs',
        path: '/optional/export-jobs',
        component: './Optional/ExportJobs',
        access: 'canReadExportJobs',
      },
    ],
  },
  {
    path: '/integrations',
    name: 'integrations',
    icon: 'api',
    routes: [
      { path: '/integrations', redirect: '/integrations/providers' },
      {
        name: 'providers',
        path: '/integrations/providers',
        component: './Integrations/Providers',
        access: 'canReadIntegrationProviders',
      },
      {
        name: 'mail',
        path: '/integrations/mail',
        component: './Integrations/Mail',
        access: 'canReadMailIntegration',
      },
      {
        name: 'sms',
        path: '/integrations/sms',
        component: './Integrations/Sms',
        access: 'canReadSmsIntegration',
      },
      {
        name: 'oauth',
        path: '/integrations/oauth',
        component: './Integrations/OAuth',
        access: 'canReadOAuthIntegration',
      },
      {
        name: 'wechat',
        path: '/integrations/wechat',
        component: './Integrations/WeChat',
        access: 'canReadWeChatIntegration',
      },
      {
        name: 'websocket',
        path: '/integrations/websocket',
        component: './Integrations/WebSocket',
        access: 'canReadWebSocketIntegration',
      },
      {
        name: 'payment',
        path: '/integrations/billing-design',
        component: './Integrations/BillingDesign',
        access: 'canReadBillingDesign',
      },
    ],
  },
  {
    path: '/redirect/*',
    component: './Redirect',
    layout: false,
    hideInMenu: true,
  },
  {
    path: '/403',
    component: './Exception/403',
    hideInMenu: true,
    name: 'exception.403',
  },
  {
    path: '/404',
    component: './Exception/404',
    hideInMenu: true,
    name: 'exception.404',
  },
  {
    path: '/500',
    component: './Exception/500',
    hideInMenu: true,
    name: 'exception.500',
  },
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    component: './Exception/404',
    path: '/*',
  },
];
