export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user/login',
        name: 'login',
        component: './user/login',
      },
      {
        path: '/user',
        redirect: '/user/login',
      },
      {
        name: 'exception.404',
        component: './Exception/404',
        path: '/user/*',
      },
    ],
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'dashboard',
    component: './Dashboard',
    access: 'canAccessDashboard',
  },
  {
    path: '/personal/profile',
    name: 'profile',
    component: './Personal/Profile',
    hideInMenu: true,
  },
  {
    path: '/system',
    name: 'system',
    icon: 'setting',
    routes: [
      { path: '/system', redirect: '/system/users' },
      {
        name: 'system.users',
        path: '/system/users',
        component: './System/Users',
        access: 'canReadUsers',
      },
      {
        name: 'system.roles',
        path: '/system/roles',
        component: './System/Roles',
        access: 'canReadRoles',
      },
      {
        name: 'system.permissions',
        path: '/system/permissions',
        component: './System/Permissions',
        access: 'canReadPermissions',
      },
      {
        name: 'system.menus',
        path: '/system/menus',
        component: './System/Menus',
        access: 'canReadMenus',
      },
      {
        name: 'system.dicts',
        path: '/system/dicts',
        component: './System/Dicts',
        access: 'canReadDicts',
      },
      {
        name: 'system.config',
        path: '/system/config',
        component: './System/Config',
        access: 'canReadSystemConfig',
      },
      {
        name: 'system.notices',
        path: '/system/notices',
        component: './System/Notices',
        access: 'canReadSystemNotices',
      },
      {
        name: 'system.depts',
        path: '/system/depts',
        component: './System/Departments',
        access: 'canReadDepartments',
      },
      {
        name: 'system.posts',
        path: '/system/posts',
        component: './System/Posts',
        access: 'canReadPosts',
      },
      {
        name: 'system.files',
        path: '/system/files',
        component: './System/Files',
        access: 'canReadFiles',
      },
    ],
  },
  {
    path: '/security',
    name: 'security',
    icon: 'safety',
    routes: [
      { path: '/security', redirect: '/security/login-logs' },
      {
        name: 'security.loginLogs',
        path: '/security/login-logs',
        component: './Security/LoginLogs',
        access: 'canReadLoginLogs',
      },
      {
        name: 'security.operationLogs',
        path: '/security/operation-logs',
        component: './Security/OperationLogs',
        access: 'canReadAuditLogs',
      },
    ],
  },
  {
    path: '/monitor',
    name: 'monitor',
    icon: 'monitor',
    routes: [
      { path: '/monitor', redirect: '/monitor/status' },
      {
        name: 'monitor.status',
        path: '/monitor/status',
        component: './Monitor/Status',
        access: 'canReadSystemStatus',
      },
      {
        name: 'monitor.version',
        path: '/monitor/version',
        component: './Monitor/Version',
        access: 'canReadVersion',
      },
      {
        name: 'monitor.queues',
        path: '/monitor/queues',
        component: './Monitor/Queues',
        access: 'canReadQueues',
      },
      {
        name: 'monitor.jobs',
        path: '/monitor/jobs',
        component: './Monitor/Jobs',
        access: 'canReadJobs',
      },
      {
        name: 'monitor.cache',
        path: '/monitor/cache',
        component: './Monitor/Cache',
        access: 'canReadCache',
      },
      {
        name: 'monitor.onlineUsers',
        path: '/monitor/online-users',
        component: './Monitor/OnlineUsers',
        access: 'canReadOnlineUsers',
      },
    ],
  },
  {
    path: '/tools',
    name: 'tools',
    icon: 'tool',
    routes: [
      { path: '/tools', redirect: '/tools/openapi' },
      {
        name: 'tools.openapi',
        path: '/tools/openapi',
        component: './Tools/OpenApi',
        access: 'canReadOpenApiStatus',
      },
      {
        name: 'tools.export',
        path: '/tools/export',
        component: './Tools/Export',
        access: 'canReadExportTools',
      },
      {
        name: 'tools.area',
        path: '/tools/area',
        component: './Tools/Area',
        access: 'canReadAreaData',
      },
      {
        name: 'tools.openforge',
        path: '/tools/openforge',
        component: './Tools/OpenForge',
        access: 'canReadOpenForge',
      },
    ],
  },
  {
    path: '/collaboration',
    name: 'collaboration',
    icon: 'team',
    routes: [
      { path: '/collaboration', redirect: '/collaboration/messages' },
      {
        name: 'collaboration.messages',
        path: '/collaboration/messages',
        component: './Collaboration/Messages',
        access: 'canReadMessages',
      },
      {
        name: 'collaboration.notices',
        path: '/collaboration/notices',
        component: './Collaboration/Notices',
        access: 'canReadNotices',
      },
      {
        name: 'collaboration.todos',
        path: '/collaboration/todos',
        component: './Collaboration/Todos',
        access: 'canReadTodos',
      },
      {
        name: 'collaboration.approvals',
        path: '/collaboration/approvals',
        component: './Collaboration/Approvals',
        access: 'canReadApprovalLite',
      },
    ],
  },
  {
    path: '/optional',
    name: 'optional',
    icon: 'appstore',
    routes: [
      { path: '/optional', redirect: '/optional/reports' },
      {
        name: 'optional.reports',
        path: '/optional/reports',
        component: './Optional/Reports',
        access: 'canReadReports',
      },
      {
        name: 'optional.exportJobs',
        path: '/optional/export-jobs',
        component: './Optional/ExportJobs',
        access: 'canReadExportJobs',
      },
    ],
  },
  {
    path: '/integrations',
    name: 'integrations',
    icon: 'api',
    routes: [
      { path: '/integrations', redirect: '/integrations/providers' },
      {
        name: 'integrations.providers',
        path: '/integrations/providers',
        component: './Integrations/Providers',
        access: 'canReadIntegrationProviders',
      },
      {
        name: 'integrations.mail',
        path: '/integrations/mail',
        component: './Integrations/Mail',
        access: 'canReadMailIntegration',
      },
      {
        name: 'integrations.sms',
        path: '/integrations/sms',
        component: './Integrations/Sms',
        access: 'canReadSmsIntegration',
      },
      {
        name: 'integrations.oauth',
        path: '/integrations/oauth',
        component: './Integrations/OAuth',
        access: 'canReadOAuthIntegration',
      },
      {
        name: 'integrations.wechat',
        path: '/integrations/wechat',
        component: './Integrations/WeChat',
        access: 'canReadWeChatIntegration',
      },
      {
        name: 'integrations.websocket',
        path: '/integrations/websocket',
        component: './Integrations/WebSocket',
        access: 'canReadWebSocketIntegration',
      },
      {
        name: 'integrations.payment',
        path: '/integrations/billing-design',
        component: './Integrations/BillingDesign',
        access: 'canReadBillingDesign',
      },
    ],
  },
  {
    path: '/403',
    component: './Exception/403',
  },
  {
    path: '/404',
    component: './Exception/404',
  },
  {
    path: '/500',
    component: './Exception/500',
  },
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    component: './Exception/404',
    path: '/*',
  },
];
