import { existsSync, readFileSync } from 'node:fs';
import {
  OPENFORGE_TEMPLATE_VERSION,
  type OpenForgeArtifactPlan,
  type OpenForgeDiffEntry,
  type OpenForgeDiffPlan,
  type OpenForgeDiffStatus,
} from '@opencore/contracts';
import { createStableHash } from '../hash/stable-hash';
import {
  buildGeneratePlan,
  OPENFORGE_DETERMINISTIC_TIMESTAMP,
} from '../planner/generate-plan';
import { evaluatePathSafety } from '../safety/path-safety';

export type BuildDiffPlanOptions = {
  schemaPath: string;
};

const GENERATED_MARKER = '@generated by OpenForge';

function getArtifactHash(artifact: OpenForgeArtifactPlan): string {
  if (artifact.contentHash) {
    return artifact.contentHash;
  }

  return createStableHash(artifact.contentPreview ?? '');
}

export function evaluateArtifactDiff(
  artifact: OpenForgeArtifactPlan,
): OpenForgeDiffEntry {
  const pathSafety = evaluatePathSafety(artifact.targetPath);

  if (pathSafety.blocked) {
    return {
      targetPath: artifact.targetPath,
      kind: artifact.kind,
      status: pathSafety.protected ? 'protected-conflict' : 'blocked',
      protected: pathSafety.protected,
      reason: pathSafety.reason ?? 'Target path is blocked by safety policy.',
      afterHash: getArtifactHash(artifact),
    };
  }

  if (!existsSync(artifact.targetPath)) {
    return {
      targetPath: artifact.targetPath,
      kind: artifact.kind,
      status: 'would-create',
      protected: false,
      reason:
        'Target path does not exist; OpenForge would create it in a later write-enabled stage.',
      afterHash: getArtifactHash(artifact),
    };
  }

  const existingContent = readFileSync(artifact.targetPath, 'utf8');
  const beforeHash = createStableHash(existingContent);
  const afterHash = getArtifactHash(artifact);

  if (beforeHash === afterHash) {
    return {
      targetPath: artifact.targetPath,
      kind: artifact.kind,
      status: 'unchanged',
      protected: false,
      reason:
        'Existing generated content already matches the planned artifact.',
      beforeHash,
      afterHash,
    };
  }

  if (!existingContent.includes(GENERATED_MARKER)) {
    return {
      targetPath: artifact.targetPath,
      kind: artifact.kind,
      status: 'protected-conflict',
      protected: true,
      reason:
        'Existing file has no OpenForge generated marker and must be reviewed manually.',
      beforeHash,
      afterHash,
    };
  }

  return {
    targetPath: artifact.targetPath,
    kind: artifact.kind,
    status: 'would-update',
    protected: false,
    reason:
      'Existing generated file would be updated in a later write-enabled stage.',
    beforeHash,
    afterHash,
  };
}

function sortDiffEntries(
  entries: readonly OpenForgeDiffEntry[],
): readonly OpenForgeDiffEntry[] {
  const statusOrder: Record<OpenForgeDiffStatus, number> = {
    blocked: 0,
    'protected-conflict': 1,
    'would-update': 2,
    'would-create': 3,
    unchanged: 4,
  };

  return [...entries].sort((left, right) => {
    const statusDelta = statusOrder[left.status] - statusOrder[right.status];

    if (statusDelta !== 0) {
      return statusDelta;
    }

    return left.targetPath.localeCompare(right.targetPath);
  });
}

export function buildDiffPlan(
  options: BuildDiffPlanOptions,
): OpenForgeDiffPlan {
  const plan = buildGeneratePlan({ schemaPath: options.schemaPath });

  return {
    moduleCode: plan.moduleCode,
    templateVersion: OPENFORGE_TEMPLATE_VERSION,
    generatedAt: OPENFORGE_DETERMINISTIC_TIMESTAMP,
    entries: sortDiffEntries(plan.artifacts.map(evaluateArtifactDiff)),
    warnings: plan.warnings,
    errors: plan.errors,
    safety: plan.safety,
  };
}
