import type {
  MenuDefinition,
  ModuleDefinition,
  PermissionDefinition,
} from './module-contract';
import type { PermissionCode } from './permission-code';

export const OPENFORGE_TEMPLATE_VERSION = 's9-openforge-mvp-v1' as const;

export const OPENFORGE_V1_TEMPLATE_VERSION =
  'openforge-default-nest-umi-v1' as const;

export const OPENFORGE_GENERATED_MARKER_SIGNATURE =
  '@generated by OpenForge' as const;

export const OPENFORGE_CONTRACT_PROTOCOL = {
  stage: 'S9',
  status: 'read-only-plan',
  ownerPackage: '@opencore/contracts',
  toolPackage: '@opencore/openforge',
  sourceRegistryPackage: '@opencore/module-registry',
  openApiSnapshotPath: 'packages/contracts/openapi/opencore-api.json',
  exampleSchemaPath: 'tools/generator/examples/core.dict.schema.json',
  planCommand:
    'pnpm openforge:plan -- --schema tools/generator/examples/core.dict.schema.json --format json',
  diffCommand:
    'pnpm openforge:diff -- --schema tools/generator/examples/core.dict.schema.json --format json',
  checkCommand: 'pnpm openforge:check',
  noWrite: true,
} as const;

export const OPENFORGE_V1_CONTRACT_PROTOCOL = {
  stage: 'OpenForge V1',
  status: 'safe-generator-contract',
  ownerPackage: '@opencore/contracts',
  toolPackage: '@opencore/openforge',
  defaultTemplatePack: OPENFORGE_V1_TEMPLATE_VERSION,
  defaultApplyMode: 'dry-run',
  requireExplicitYesForWrites: true,
  requireGeneratedMarkerForUpdate: true,
  manifestDirectory: '.openforge/manifests',
  rollbackFromManifestOnly: true,
} as const;

export type OpenForgePlanFormat = 'json' | 'markdown';

export type OpenForgeValidationSeverity = 'error' | 'warning';

export type OpenForgeValidationIssue = {
  severity: OpenForgeValidationSeverity;
  path: string;
  message: string;
};

export const OPENFORGE_FIELD_TYPES = [
  'boolean',
  'datetime',
  'enum',
  'file',
  'json',
  'number',
  'relation',
  'string',
  'text',
] as const;

export type OpenForgeFieldType = (typeof OPENFORGE_FIELD_TYPES)[number];

export type OpenForgeRelationCardinality = 'many' | 'one';

export type OpenForgeFieldRelation = {
  targetModule: ModuleDefinition['code'];
  targetResource: string;
  cardinality: OpenForgeRelationCardinality;
  displayField?: string;
};

export type OpenForgeFieldSchema = {
  name: string;
  title: string;
  type: OpenForgeFieldType;
  required?: boolean;
  list?: boolean;
  form?: boolean;
  detail?: boolean;
  sensitive?: boolean;
  detailOnly?: boolean;
  permissionCode?: PermissionCode;
  enumValues?: readonly string[];
  relation?: OpenForgeFieldRelation;
  fileAccept?: readonly string[];
};

export type OpenForgeIndexHint = {
  name: string;
  fields: readonly string[];
  unique?: boolean;
  reason: string;
};

export type OpenForgeFieldSelection = {
  fields: readonly string[];
};

export type OpenForgeSortDirection = 'asc' | 'desc';

export type OpenForgeSortSpec = {
  field: string;
  direction: OpenForgeSortDirection;
};

export type OpenForgeManualSchema = {
  schemaVersion?: 'openforge.schema.v1';
  moduleCode: ModuleDefinition['code'];
  resource: string;
  title: string;
  description?: string;
  fields: readonly OpenForgeFieldSchema[];
  relations?: readonly OpenForgeFieldRelation[];
  indexes?: readonly OpenForgeIndexHint[];
  list: {
    title: string;
    columns: readonly string[];
    defaultPageSize?: number;
  };
  filter?: OpenForgeFieldSelection;
  sort?: {
    default?: OpenForgeSortSpec;
    fields?: readonly string[];
  };
  form: {
    title: string;
    fields: readonly string[];
    mode?: 'drawer' | 'modal';
  };
  detail: {
    title: string;
    fields: readonly string[];
  };
  actions: readonly string[];
  permissions: readonly PermissionCode[];
  openapi: {
    tags: readonly string[];
    paths?: readonly string[];
  };
  admin: {
    basePath: `/${string}`;
    menuKey?: string;
    targetPaths?: readonly string[];
  };
  sdk?: {
    clientName: string;
    generatedPath: string;
    targetPaths?: readonly string[];
  };
  tests?: {
    api?: string;
    admin?: string;
    e2e?: string;
  };
  docs?: {
    moduleDoc: string;
    runbook: string;
    patchReview?: string;
  };
  export?: {
    enabled: boolean;
    columns: readonly string[];
    maxRows?: number;
  };
  storage?: {
    enabled: boolean;
    fields?: readonly string[];
  };
  audit?: {
    enabled: boolean;
    actions: readonly string[];
  };
  prisma?: {
    writeSchema?: boolean;
    modelName?: string;
    draftPath?: string;
    migrationHintPath?: string;
  };
};

export type OpenForgeInputSnapshot = {
  generatedAt: string;
  registryHash: string;
  openApiHash: string;
  schemaHash: string;
  module: Pick<
    ModuleDefinition,
    'apiTags' | 'code' | 'layer' | 'stage' | 'title'
  >;
  permissions: readonly PermissionDefinition[];
  menus: readonly MenuDefinition[];
};

export type OpenForgeArtifactKind =
  | 'api.controller'
  | 'api.dto'
  | 'api.module'
  | 'api.repository'
  | 'api.spec'
  | 'api.service'
  | 'admin.descriptions'
  | 'admin.detail'
  | 'admin.drawerForm'
  | 'admin.exportButton'
  | 'admin.form'
  | 'admin.listPage'
  | 'admin.modalForm'
  | 'admin.proTablePage'
  | 'admin.smokeTest'
  | 'docs.admin-doc'
  | 'docs.api-doc'
  | 'docs.fragment'
  | 'docs.module-doc'
  | 'docs.patch-review'
  | 'docs.runbook'
  | 'patch.admin-access'
  | 'patch.admin-route'
  | 'patch.app-module'
  | 'patch.module-registry'
  | 'patch.sdk-index'
  | 'prisma.hint'
  | 'prisma.migration-hint'
  | 'prisma.model-draft'
  | 'sdk.client'
  | 'sdk.generated-index'
  | 'sdk.spec'
  | 'sdk.types'
  | 'test.admin'
  | 'test.api';

export const OPENFORGE_ARTIFACT_KINDS = [
  'api.controller',
  'api.dto',
  'api.module',
  'api.repository',
  'api.spec',
  'api.service',
  'admin.descriptions',
  'admin.detail',
  'admin.drawerForm',
  'admin.exportButton',
  'admin.form',
  'admin.listPage',
  'admin.modalForm',
  'admin.proTablePage',
  'admin.smokeTest',
  'docs.admin-doc',
  'docs.api-doc',
  'docs.fragment',
  'docs.module-doc',
  'docs.patch-review',
  'docs.runbook',
  'patch.admin-access',
  'patch.admin-route',
  'patch.app-module',
  'patch.module-registry',
  'patch.sdk-index',
  'prisma.hint',
  'prisma.migration-hint',
  'prisma.model-draft',
  'sdk.client',
  'sdk.generated-index',
  'sdk.spec',
  'sdk.types',
  'test.admin',
  'test.api',
] as const satisfies readonly OpenForgeArtifactKind[];

export type OpenForgeArtifactAction =
  | 'hint'
  | 'skip'
  | 'would-create'
  | 'would-update';

export type OpenForgeOverwritePolicy =
  | 'generated-marker-required'
  | 'manual-review'
  | 'never';

export type OpenForgeArtifactPlan = {
  kind: OpenForgeArtifactKind;
  targetPath: string;
  action: OpenForgeArtifactAction;
  protected: boolean;
  overwritePolicy: OpenForgeOverwritePolicy;
  contentHash?: string;
  contentPreview?: string;
  reason: string;
};

export type OpenForgeSafetyPolicy = {
  noWrite: true;
  dryRunOnly: true;
  protectedPaths: readonly string[];
  forbiddenPathPatterns: readonly string[];
  requireGeneratedMarkerForUpdate: true;
  blockPrismaSchemaWrites: true;
  blockPrismaMigrations: true;
  blockP4P5Modules: true;
};

export type OpenForgePlan = {
  moduleCode: ModuleDefinition['code'];
  templateVersion: typeof OPENFORGE_TEMPLATE_VERSION;
  inputSnapshot: OpenForgeInputSnapshot;
  schemaHash: string;
  openApiSnapshotHash: string;
  registrySnapshotHash: string;
  artifacts: readonly OpenForgeArtifactPlan[];
  permissions: readonly PermissionCode[];
  menus: readonly MenuDefinition[];
  openapiTags: readonly string[];
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
  nextCommands: readonly string[];
  safety: OpenForgeSafetyPolicy;
};

export type OpenForgeDiffStatus =
  | 'blocked'
  | 'protected-conflict'
  | 'unchanged'
  | 'would-create'
  | 'would-update';

export type OpenForgeDiffEntry = {
  targetPath: string;
  kind: OpenForgeArtifactKind;
  status: OpenForgeDiffStatus;
  protected: boolean;
  reason: string;
  beforeHash?: string;
  afterHash?: string;
};

export type OpenForgeDiffPlan = {
  moduleCode: ModuleDefinition['code'];
  templateVersion: typeof OPENFORGE_TEMPLATE_VERSION;
  generatedAt: string;
  entries: readonly OpenForgeDiffEntry[];
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
  safety: OpenForgeSafetyPolicy;
};

export type OpenForgePreflightReport = {
  templateVersion: typeof OPENFORGE_TEMPLATE_VERSION;
  generatedAt: string;
  schemaPath: string;
  moduleCode: ModuleDefinition['code'];
  valid: boolean;
  noWrite: true;
  registry: {
    valid: boolean;
    moduleCount: number;
    permissionCount: number;
    menuCount: number;
    issueCount: number;
  };
  openApi: {
    snapshotPath: string;
    pathCount: number;
    operationCount: number;
    tagCount: number;
    schemaCount: number;
  };
  safety: OpenForgeSafetyPolicy;
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
};

export type OpenForgeArtifactContent =
  | {
      format: 'json';
      value: unknown;
    }
  | {
      format: 'markdown' | 'text' | 'typescript';
      value: string;
    };

export type OpenForgeGeneratedMarker = {
  signature: typeof OPENFORGE_GENERATED_MARKER_SIGNATURE;
  templateVersion: string;
  schemaHash: string;
  moduleCode: ModuleDefinition['code'];
  artifactKind: OpenForgeArtifactKind;
  generatedAt: string;
};

export type OpenForgeGeneratedFile = {
  targetPath: string;
  artifactKind: OpenForgeArtifactKind;
  content: OpenForgeArtifactContent;
  contentHash: string;
  marker: OpenForgeGeneratedMarker;
};

export type OpenForgeVirtualFile = OpenForgeGeneratedFile & {
  isGenerated: boolean;
  isPatchOnly: boolean;
  reason: string;
};

export type OpenForgeOutputPolicy = {
  outputRoot: string;
  allowedArtifactKinds: readonly OpenForgeArtifactKind[];
  blockedArtifactKinds: readonly OpenForgeArtifactKind[];
};

export type OpenForgeApplyMode = 'dry-run' | 'write';

export type OpenForgeWritePolicy = {
  defaultMode: 'dry-run';
  requireExplicitYes: true;
  allowCreate: true;
  allowUpdateGenerated: true;
  blockHumanAuthored: true;
  generatedMarkerRequired: true;
  protectedPaths: readonly string[];
  manualPatchOnlyPaths: readonly string[];
  blockedPathPatterns: readonly string[];
  blockEnvFiles: true;
  blockPrismaSchema: true;
  blockPrismaMigrations: true;
};

export type OpenForgeGeneratorConfig = {
  templatePack: string;
  templateVersion: string;
  outputRoot: string;
  applyMode: OpenForgeApplyMode;
  overwritePolicy: OpenForgeOverwritePolicy;
  generatedMarkerRequired: boolean;
  protectedPaths: readonly string[];
  manualPatchOnlyPaths: readonly string[];
  allowedArtifactKinds: readonly OpenForgeArtifactKind[];
  blockedArtifactKinds: readonly OpenForgeArtifactKind[];
  strictOpenApiTags: boolean;
  strictPermissionCodes: boolean;
  outputPolicy: OpenForgeOutputPolicy;
  writePolicy: OpenForgeWritePolicy;
};

export type OpenForgeTemplateRenderContext = {
  schema: OpenForgeManualSchema;
  config: OpenForgeGeneratorConfig;
  module: Pick<
    ModuleDefinition,
    'apiTags' | 'code' | 'layer' | 'stage' | 'title'
  >;
  schemaHash: string;
  templateVersion: string;
  permissions: readonly PermissionDefinition[];
  menus: readonly MenuDefinition[];
  openapiTags: readonly string[];
};

export type OpenForgeTemplateDefinition = {
  id: string;
  artifactKind: OpenForgeArtifactKind;
  description: string;
  targetPathPattern: string;
  patchOnly: boolean;
};

export type OpenForgeTemplatePack = {
  id: string;
  name: string;
  version: string;
  templates: readonly OpenForgeTemplateDefinition[];
  supportedArtifactKinds: readonly OpenForgeArtifactKind[];
};

export type OpenForgePatchEntry = {
  targetPath: string;
  patchPath: string;
  artifactKind: OpenForgeArtifactKind;
  manualInsertionPoint: string;
  reason: string;
  risk: string;
  verificationCommands: readonly string[];
};

export type OpenForgePatchPlan = {
  moduleCode: ModuleDefinition['code'];
  templateVersion: string;
  generatedAt: string;
  entries: readonly OpenForgePatchEntry[];
  warnings: readonly OpenForgeValidationIssue[];
};

export type OpenForgeManifestEntryAction =
  | 'blocked'
  | 'created'
  | 'skipped'
  | 'updated';

export type OpenForgeManifestRollbackAction = 'delete' | 'none' | 'restore';

export type OpenForgeManifestEntry = {
  targetPath: string;
  artifactKind: OpenForgeArtifactKind;
  action: OpenForgeManifestEntryAction;
  rollbackAction: OpenForgeManifestRollbackAction;
  beforeHash?: string;
  afterHash?: string;
  backupPath?: string;
  marker?: OpenForgeGeneratedMarker;
};

export type OpenForgeManifest = {
  id: string;
  createdAt: string;
  command: string;
  schemaPath: string;
  moduleCode: ModuleDefinition['code'];
  templateVersion: string;
  inputHashes: {
    schemaHash: string;
    registryHash: string;
    openApiHash: string;
    configHash?: string;
  };
  entries: readonly OpenForgeManifestEntry[];
};

export type OpenForgeApplyRequest = {
  command: string;
  schemaPath: string;
  configPath?: string;
  mode: OpenForgeApplyMode;
  yes: boolean;
  config: OpenForgeGeneratorConfig;
};

export type OpenForgeApplyResult = {
  mode: OpenForgeApplyMode;
  applied: boolean;
  manifestPath?: string;
  manifest?: OpenForgeManifest;
  entries: readonly OpenForgeManifestEntry[];
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
};

export type OpenForgeRollbackRequest = {
  manifestPath: string;
  mode: OpenForgeApplyMode;
  yes: boolean;
};

export type OpenForgeRollbackEntryAction =
  | 'blocked'
  | 'delete'
  | 'restore'
  | 'skip';

export type OpenForgeRollbackPlanEntry = {
  targetPath: string;
  artifactKind: OpenForgeArtifactKind;
  action: OpenForgeRollbackEntryAction;
  reason: string;
  beforeHash?: string;
  afterHash?: string;
};

export type OpenForgeRollbackPlan = {
  manifest: OpenForgeManifest;
  mode: OpenForgeApplyMode;
  entries: readonly OpenForgeRollbackPlanEntry[];
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
};

export type OpenForgeRollbackAudit = {
  id: string;
  createdAt: string;
  command: string;
  manifestPath: string;
  manifestId: string;
  moduleCode: ModuleDefinition['code'];
  templateVersion: string;
  entries: readonly OpenForgeRollbackPlanEntry[];
};

export type OpenForgeRollbackResult = {
  mode: OpenForgeApplyMode;
  rolledBack: boolean;
  entries: readonly OpenForgeRollbackPlanEntry[];
  manifest?: OpenForgeManifest;
  auditPath?: string;
  audit?: OpenForgeRollbackAudit;
  warnings: readonly OpenForgeValidationIssue[];
  errors: readonly OpenForgeValidationIssue[];
};

function createOpenForgeContractIssue(
  path: string,
  message: string,
): OpenForgeValidationIssue {
  return {
    severity: 'error',
    path,
    message,
  };
}

function cleanMarkerLine(line: string): string {
  return line
    .replace(/^\s*\/\*+/, '')
    .replace(/\*+\/\s*$/, '')
    .replace(/^\s*(?:\*|\/\/|#|<!--|-->)\s?/, '')
    .trim();
}

function parseMarkerField(line: string): readonly [string, string] | null {
  const separatorIndex =
    line.includes('=') &&
    (!line.includes(':') || line.indexOf('=') < line.indexOf(':'))
      ? line.indexOf('=')
      : line.indexOf(':');

  if (separatorIndex === -1) {
    return null;
  }

  const key = line.slice(0, separatorIndex).trim();
  const value = line.slice(separatorIndex + 1).trim();

  if (!key || !value) {
    return null;
  }

  return [key, value] as const;
}

export function isOpenForgeArtifactKind(
  value: string,
): value is OpenForgeArtifactKind {
  return (OPENFORGE_ARTIFACT_KINDS as readonly string[]).includes(value);
}

export function formatOpenForgeGeneratedMarker(
  marker: OpenForgeGeneratedMarker,
): string {
  return [
    OPENFORGE_GENERATED_MARKER_SIGNATURE,
    `templateVersion=${marker.templateVersion}`,
    `schemaHash=${marker.schemaHash}`,
    `moduleCode=${marker.moduleCode}`,
    `artifactKind=${marker.artifactKind}`,
    `generatedAt=${marker.generatedAt}`,
  ].join('\n');
}

export function parseOpenForgeGeneratedMarker(
  content: string,
): OpenForgeGeneratedMarker | null {
  const lines = content.split(/\r?\n/).map(cleanMarkerLine);
  const markerIndex = lines.findIndex(
    (line) => line === OPENFORGE_GENERATED_MARKER_SIGNATURE,
  );

  if (markerIndex === -1) {
    return null;
  }

  const fields = new Map<string, string>();
  const expectedKeys = new Set([
    'templateVersion',
    'schemaHash',
    'moduleCode',
    'artifactKind',
    'generatedAt',
  ]);

  for (const line of lines.slice(markerIndex + 1, markerIndex + 12)) {
    if (!line && fields.size > 0) {
      break;
    }

    const field = parseMarkerField(line);

    if (!field) {
      continue;
    }

    const [key, value] = field;

    if (expectedKeys.has(key)) {
      fields.set(key, value);
    }
  }

  const artifactKind = fields.get('artifactKind');

  if (!artifactKind || !isOpenForgeArtifactKind(artifactKind)) {
    return null;
  }

  const templateVersion = fields.get('templateVersion');
  const schemaHash = fields.get('schemaHash');
  const moduleCode = fields.get('moduleCode');
  const generatedAt = fields.get('generatedAt');

  if (!templateVersion || !schemaHash || !moduleCode || !generatedAt) {
    return null;
  }

  return {
    signature: OPENFORGE_GENERATED_MARKER_SIGNATURE,
    templateVersion,
    schemaHash,
    moduleCode: moduleCode as ModuleDefinition['code'],
    artifactKind,
    generatedAt,
  };
}

export function validateOpenForgeApplyRequest(
  request: OpenForgeApplyRequest,
): readonly OpenForgeValidationIssue[] {
  const issues: OpenForgeValidationIssue[] = [];

  if (request.mode === 'write' && !request.yes) {
    issues.push(
      createOpenForgeContractIssue(
        'yes',
        'OpenForge write mode requires explicit --yes confirmation.',
      ),
    );
  }

  if (request.config.applyMode === 'write' && request.mode !== 'write') {
    issues.push(
      createOpenForgeContractIssue(
        'mode',
        'OpenForge config write mode must be paired with a write apply request.',
      ),
    );
  }

  if (!request.config.generatedMarkerRequired) {
    issues.push(
      createOpenForgeContractIssue(
        'config.generatedMarkerRequired',
        'OpenForge updates must require a generated marker.',
      ),
    );
  }

  if (!request.config.writePolicy.requireExplicitYes) {
    issues.push(
      createOpenForgeContractIssue(
        'config.writePolicy.requireExplicitYes',
        'OpenForge write policy must require explicit confirmation.',
      ),
    );
  }

  if (!request.config.writePolicy.generatedMarkerRequired) {
    issues.push(
      createOpenForgeContractIssue(
        'config.writePolicy.generatedMarkerRequired',
        'OpenForge write policy must require generated markers for updates.',
      ),
    );
  }

  return issues;
}
