import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { applyOpenForge } from './apply-writer';

function createTempRepo(): string {
  return mkdtempSync(join(tmpdir(), 'openforge-apply-'));
}

function removeTempRepo(repoRoot: string): void {
  rmSync(repoRoot, { force: true, recursive: true });
}

function writeManualFile(repoRoot: string, targetPath: string): void {
  const absolutePath = join(repoRoot, targetPath);

  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, 'manual file without OpenForge marker\n');
}

describe('OpenForge safe apply writer', () => {
  const schemaPath = 'tools/generator/examples/core.dict.v1.schema.json';

  it('defaults to dry-run and writes no files or manifests', () => {
    const repoRoot = createTempRepo();

    try {
      const result = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'dry-run',
      });

      expect(result).toMatchObject({
        mode: 'dry-run',
        applied: false,
        errors: [],
      });
      expect(result.entries.map((entry) => entry.action)).toEqual(
        expect.arrayContaining(['created']),
      );
      expect(
        existsSync(
          join(
            repoRoot,
            'apps/api/src/modules/generated/core/dict/dict.controller.ts',
          ),
        ),
      ).toBe(false);
      expect(existsSync(join(repoRoot, '.openforge'))).toBe(false);
    } finally {
      removeTempRepo(repoRoot);
    }
  });

  it('writes generated files and a manifest only with explicit yes', () => {
    const repoRoot = createTempRepo();

    try {
      const result = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
      });
      const controllerPath = join(
        repoRoot,
        'apps/api/src/modules/generated/core/dict/dict.controller.ts',
      );

      expect(result.applied).toBe(true);
      expect(result.manifestPath).toBe(
        '.openforge/manifests/20260610T000000000Z-core.dict-a7ab4f39.json',
      );
      expect(existsSync(controllerPath)).toBe(true);
      expect(readFileSync(controllerPath, 'utf8')).toContain(
        '@generated by OpenForge',
      );
      expect(existsSync(join(repoRoot, result.manifestPath ?? 'missing'))).toBe(
        true,
      );
      expect(
        readFileSync(join(repoRoot, result.manifestPath ?? 'missing'), 'utf8'),
      ).not.toContain('.env.opencore.local');
    } finally {
      removeTempRepo(repoRoot);
    }
  });

  it('blocks human-authored conflicts before writing any files', () => {
    const repoRoot = createTempRepo();
    const controllerTarget =
      'apps/api/src/modules/generated/core/dict/dict.controller.ts';

    try {
      writeManualFile(repoRoot, controllerTarget);

      const result = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
      });

      expect(result.applied).toBe(false);
      expect(result.errors.map((issue) => issue.message)).toEqual(
        expect.arrayContaining([
          'Target path is blocked or conflicts with a human-authored file.',
        ]),
      );
      expect(readFileSync(join(repoRoot, controllerTarget), 'utf8')).toBe(
        'manual file without OpenForge marker\n',
      );
      expect(
        existsSync(
          join(
            repoRoot,
            'apps/api/src/modules/generated/core/dict/dict.dto.ts',
          ),
        ),
      ).toBe(false);
      expect(existsSync(join(repoRoot, '.openforge'))).toBe(false);
    } finally {
      removeTempRepo(repoRoot);
    }
  });

  it('updates existing generated files that still contain a valid marker', () => {
    const repoRoot = createTempRepo();
    const controllerTarget =
      'apps/api/src/modules/generated/core/dict/dict.controller.ts';
    const controllerPath = join(repoRoot, controllerTarget);

    try {
      const first = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
      });

      expect(first.applied).toBe(true);

      writeFileSync(
        controllerPath,
        `${readFileSync(controllerPath, 'utf8')}\n// generated file edit\n`,
      );

      const second = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
      });

      expect(second.applied).toBe(true);
      expect(
        second.entries.find((entry) => entry.targetPath === controllerTarget),
      ).toMatchObject({
        action: 'updated',
        rollbackAction: 'restore',
      });
      expect(readFileSync(controllerPath, 'utf8')).not.toContain(
        'generated file edit',
      );
    } finally {
      removeTempRepo(repoRoot);
    }
  });

  it('rejects write mode without explicit yes', () => {
    const repoRoot = createTempRepo();

    try {
      const result = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: false,
      });

      expect(result.applied).toBe(false);
      expect(result.errors).toEqual(
        expect.arrayContaining([
          {
            severity: 'error',
            path: 'yes',
            message:
              'OpenForge write mode requires explicit --yes confirmation.',
          },
        ]),
      );
      expect(existsSync(join(repoRoot, '.openforge'))).toBe(false);
    } finally {
      removeTempRepo(repoRoot);
    }
  });
});
