import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: 'OpenCore Admin',
  },
  routes: [
    {
      path: '/',
      redirect: '/dashboard',
    },
    {
      name: 'Dashboard',
      path: '/dashboard',
      component: './Dashboard',
      access: 'canAccessDashboard',
    },
    {
      name: 'OpenAPI',
      path: '/tools/openapi',
      component: './Tools/OpenApi',
      access: 'canReadOpenApiStatus',
    },
    {
      name: 'Users',
      path: '/system/users',
      component: './System/Users',
      access: 'canReadUsers',
    },
    {
      name: 'Roles',
      path: '/system/roles',
      component: './System/Roles',
      access: 'canReadRoles',
    },
    {
      name: 'Permissions',
      path: '/system/permissions',
      component: './System/Permissions',
      access: 'canReadPermissions',
    },
    {
      name: 'Menus',
      path: '/system/menus',
      component: './System/Menus',
      access: 'canReadMenus',
    },
    {
      name: 'Dictionaries',
      path: '/system/dicts',
      component: './System/Dicts',
      access: 'canReadDicts',
    },
    {
      name: 'System Config',
      path: '/system/config',
      component: './System/Config',
      access: 'canReadSystemConfig',
    },
    {
      name: 'File Center',
      path: '/system/files',
      component: './System/Files',
      access: 'canReadFiles',
    },
    {
      name: 'Login Logs',
      path: '/security/login-logs',
      component: './Security/LoginLogs',
      access: 'canReadLoginLogs',
    },
    {
      name: 'Operation Logs',
      path: '/security/operation-logs',
      component: './Security/OperationLogs',
      access: 'canReadAuditLogs',
    },
    {
      name: 'System Status',
      path: '/monitor/status',
      component: './Monitor/Status',
      access: 'canReadSystemStatus',
    },
    {
      name: 'Version',
      path: '/monitor/version',
      component: './Monitor/Version',
      access: 'canReadVersion',
    },
    {
      name: 'Queues',
      path: '/monitor/queues',
      component: './Monitor/Queues',
      access: 'canReadQueues',
    },
    {
      name: 'Export Tools',
      path: '/tools/export',
      component: './Tools/Export',
      access: 'canReadExportTools',
    },
    {
      name: 'OpenForge',
      path: '/tools/openforge',
      component: './Tools/OpenForge',
      access: 'canReadOpenForge',
    },
    {
      name: 'Messages',
      path: '/collaboration/messages',
      component: './Collaboration/Messages',
      access: 'canReadMessages',
    },
    {
      name: 'Notices',
      path: '/collaboration/notices',
      component: './Collaboration/Notices',
      access: 'canReadNotices',
    },
    {
      name: 'Todos',
      path: '/collaboration/todos',
      component: './Collaboration/Todos',
      access: 'canReadTodos',
    },
    {
      name: 'Approval Lite',
      path: '/collaboration/approvals',
      component: './Collaboration/Approvals',
      access: 'canReadApprovalLite',
    },
    {
      name: 'Jobs',
      path: '/monitor/jobs',
      component: './Monitor/Jobs',
      access: 'canReadJobs',
    },
    {
      name: 'Cache',
      path: '/monitor/cache',
      component: './Monitor/Cache',
      access: 'canReadCache',
    },
    {
      name: 'Online Users',
      path: '/monitor/online-users',
      component: './Monitor/OnlineUsers',
      access: 'canReadOnlineUsers',
    },
    {
      name: 'Reports',
      path: '/optional/reports',
      component: './Optional/Reports',
      access: 'canReadReports',
    },
    {
      name: 'Export Jobs',
      path: '/optional/export-jobs',
      component: './Optional/ExportJobs',
      access: 'canReadExportJobs',
    },
    {
      name: 'Providers',
      path: '/integrations/providers',
      component: './Integrations/Providers',
      access: 'canReadIntegrationProviders',
    },
    {
      name: 'Mail',
      path: '/integrations/mail',
      component: './Integrations/Mail',
      access: 'canReadMailIntegration',
    },
    {
      name: 'SMS',
      path: '/integrations/sms',
      component: './Integrations/Sms',
      access: 'canReadSmsIntegration',
    },
    {
      name: 'OAuth',
      path: '/integrations/oauth',
      component: './Integrations/OAuth',
      access: 'canReadOAuthIntegration',
    },
    {
      name: 'WeChat',
      path: '/integrations/wechat',
      component: './Integrations/WeChat',
      access: 'canReadWeChatIntegration',
    },
    {
      name: 'WebSocket',
      path: '/integrations/websocket',
      component: './Integrations/WebSocket',
      access: 'canReadWebSocketIntegration',
    },
    {
      name: 'Payment',
      path: '/integrations/billing-design',
      component: './Integrations/BillingDesign',
      access: 'canReadBillingDesign',
    },
    {
      path: '/403',
      component: './Exception/403',
    },
    {
      path: '/404',
      component: './Exception/404',
    },
    {
      path: '/500',
      component: './Exception/500',
    },
    {
      path: '*',
      component: './Exception/404',
    },
  ],
  npmClient: 'pnpm',
  utoopack: {},
});
