import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { applyOpenForge } from '../apply/apply-writer';
import { buildDiffPlan } from '../diff/diff-plan';
import { buildGeneratePlan } from '../planner/generate-plan';
import { rollbackOpenForge } from '../rollback/rollback-engine';

function createTempRepo(): string {
  return mkdtempSync(join(tmpdir(), 'openforge-generated-e2e-'));
}

function removeTempRepo(repoRoot: string): void {
  rmSync(repoRoot, { force: true, recursive: true });
}

describe('OpenForge generated module e2e', () => {
  const schemaPath = 'tools/generator/examples/core.dict.v1.schema.json';
  const controllerTarget =
    'apps/api/src/modules/generated/core/dict/dict.controller.ts';
  const sdkClientTarget = 'packages/sdk/src/generated/dict-client.ts';
  const runbookTarget = 'docs/generated/openforge/core.dict-runbook.md';

  it('plans, diffs, applies, verifies idempotency, blocks conflicts, and rolls back in temp repos', () => {
    const repoRoot = createTempRepo();
    const conflictRepoRoot = createTempRepo();

    try {
      const plan = buildGeneratePlan({ schemaPath });
      const diff = buildDiffPlan({ schemaPath, repoRoot });

      expect(plan.errors).toEqual([]);
      expect(plan.artifacts.length).toBeGreaterThan(0);
      expect(diff.errors).toEqual([]);
      expect(diff.entries.map((entry) => entry.status)).toEqual(
        expect.arrayContaining(['would-create']),
      );

      const firstApply = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
        command: `pnpm openforge:apply -- --schema ${schemaPath} --yes`,
      });

      expect(firstApply).toMatchObject({
        mode: 'write',
        applied: true,
        errors: [],
      });
      expect(existsSync(join(repoRoot, controllerTarget))).toBe(true);
      expect(readFileSync(join(repoRoot, controllerTarget), 'utf8')).toContain(
        '@generated by OpenForge',
      );
      expect(existsSync(join(repoRoot, sdkClientTarget))).toBe(true);
      expect(existsSync(join(repoRoot, runbookTarget))).toBe(true);
      expect(existsSync(join(repoRoot, firstApply.manifestPath ?? ''))).toBe(
        true,
      );

      const secondApply = applyOpenForge({
        schemaPath,
        repoRoot,
        mode: 'write',
        yes: true,
        command: `pnpm openforge:apply -- --schema ${schemaPath} --yes`,
      });

      expect(secondApply).toMatchObject({
        mode: 'write',
        applied: false,
        errors: [],
      });
      expect(secondApply.manifestPath).toBeUndefined();
      expect(new Set(secondApply.entries.map((entry) => entry.action))).toEqual(
        new Set(['skipped']),
      );

      const conflictApply = applyOpenForge({
        schemaPath,
        repoRoot: conflictRepoRoot,
        mode: 'write',
        yes: true,
      });

      expect(conflictApply.applied).toBe(true);
      writeFileSync(
        join(conflictRepoRoot, controllerTarget),
        'manual takeover without OpenForge marker\n',
      );

      const blockedApply = applyOpenForge({
        schemaPath,
        repoRoot: conflictRepoRoot,
        mode: 'write',
        yes: true,
      });

      expect(blockedApply.applied).toBe(false);
      expect(blockedApply.errors.map((issue) => issue.message)).toEqual(
        expect.arrayContaining([
          'Target path is blocked or conflicts with a human-authored file.',
        ]),
      );
      expect(
        readFileSync(join(conflictRepoRoot, controllerTarget), 'utf8'),
      ).toBe('manual takeover without OpenForge marker\n');

      const rollback = rollbackOpenForge({
        manifestPath: firstApply.manifestPath ?? 'missing',
        repoRoot,
        mode: 'write',
        yes: true,
        command: `pnpm openforge:rollback -- --manifest ${firstApply.manifestPath} --yes`,
      });

      expect(rollback).toMatchObject({
        mode: 'write',
        rolledBack: true,
        errors: [],
      });
      expect(existsSync(join(repoRoot, controllerTarget))).toBe(false);
      expect(existsSync(join(repoRoot, sdkClientTarget))).toBe(false);
      expect(existsSync(join(repoRoot, runbookTarget))).toBe(false);
      expect(existsSync(join(repoRoot, rollback.auditPath ?? ''))).toBe(true);
    } finally {
      removeTempRepo(repoRoot);
      removeTempRepo(conflictRepoRoot);
    }
  });
});
